// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// gig_cpp
Rcpp::NumericVector gig_cpp(Rcpp::NumericVector p, Rcpp::NumericVector a, Rcpp::NumericVector b);
RcppExport SEXP rGIG_gig_cpp(SEXP pSEXP, SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type p(pSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type a(aSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type b(bSEXP);
    __result = Rcpp::wrap(gig_cpp(p, a, b));
    return __result;
END_RCPP
}
