# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Rgig wrapper for the c++ code simulating gig
#' 
#' @param a - (nx1 - double ) input parameter for gig  
#' @param b - (nx1 - double ) input parameter for gig
#' @param p - (nx1 - double)  input parameter for gig
#' @return (nx1 - double)
gig_cpp <- function(p, a, b) {
    .Call('rGIG_gig_cpp', PACKAGE = 'rGIG', p, a, b)
}

